"""UI-string catalog and language switch for ccbot's user-facing text.

ccbot's chrome — buttons, status lines, error messages, /command
descriptions, dashboards, notifications — is bilingual (ru/en). The
language is a single GLOBAL setting (single-user bot), held here as a
module-level `_current_lang` that `set_language()` updates; call sites
just call `tr("some.key")` and get the active language with **no `lang`
parameter threading**. Because the setting is global this module-level
state is legitimate — there is no per-topic context to carry.

Scope: only ccbot's OWN strings. The agent's replies (generated by
Claude Code, merely relayed) and agent-directed text (voice protocol
directives) are NOT translated here.

`STRINGS[key] = {"ru": ..., "en": ...}`. `tr` falls back to ru, then to
the key itself, so a not-yet-migrated string degrades to Russian rather
than crashing — the catalog can be filled in incrementally.

Key naming: dotted, namespaced by area (`menu.server`, `cmd.status`,
`ctx.alert`, `panel.refresh`, …) so additions
from different modules never collide.
"""

from typing import Final

LANGUAGES: Final[tuple[str, ...]] = ("ru", "en")
DEFAULT_LANGUAGE: Final[str] = "ru"

# Active UI language. Mutated only by set_language (called by
# SessionManager on state load and on /lang). Module-global is correct
# here precisely because the language is one global setting.
_current_lang: str = DEFAULT_LANGUAGE


def set_language(lang: str) -> None:
    """Set the active UI language. Unknown codes fall back to the default."""
    global _current_lang
    _current_lang = lang if lang in LANGUAGES else DEFAULT_LANGUAGE


def current_language() -> str:
    return _current_lang


def register(strings: dict[str, dict[str, str]]) -> None:
    """Merge plugin-contributed catalog entries into ``STRINGS``.

    Lets an optional plugin own its user-facing strings (namespaced by area)
    without the core catalog naming the plugin. Called once at startup by
    ``plugins.register_i18n``; last writer wins on a key clash.
    """
    STRINGS.update(strings)


def tr(key: str, /, **fmt: object) -> str:
    """Translate `key` into the active language, then `str.format(**fmt)`.

    Resolution: active language → ru → first available → the key itself
    (so a missing entry is visible, never a crash). A `.format` that
    raises on a bad placeholder returns the unformatted text rather than
    propagating — a UI string is never worth a 500.
    """
    entry = STRINGS.get(key)
    if entry is None:
        return key
    text = (
        entry.get(_current_lang) or entry.get("ru") or next(iter(entry.values()), key)
    )
    if fmt:
        try:
            return text.format(**fmt)
        except (KeyError, IndexError, ValueError):
            return text
    return text


def all_variants(key: str) -> list[str]:
    """Every language's text for `key` (for matching a label regardless of
    the language it was rendered in — e.g. the persistent menu buttons,
    whose tap arrives as plain text and must route in either language)."""
    return list(STRINGS.get(key, {}).values())


# ---------------------------------------------------------------------------
# Catalog. Infra strings are seeded here; per-module UI strings are appended
# below (one block per source module) as the migration proceeds. Keep blocks
# grouped by namespace so it's obvious which module owns which keys.
# ---------------------------------------------------------------------------
STRINGS: dict[str, dict[str, str]] = {
    # -- Persistent menu (ReplyKeyboard) --------------------------------
    "menu.server": {"ru": "🖥️ Сервер", "en": "🖥️ Server"},
    "menu.agent": {"ru": "👾 Агент", "en": "👾 Agent"},
    "menu.pinned": {"ru": "👾 Меню закреплено", "en": "👾 Menu pinned"},
    # -- /lang ----------------------------------------------------------
    "lang.changed": {
        "ru": "🌐 Язык интерфейса: русский",
        "en": "🌐 Interface language: English",
    },
    "lang.usage": {
        "ru": "🌐 Язык интерфейса: *русский*\nПереключить: /lang en",
        "en": "🌐 Interface language: *English*\nSwitch: /lang ru",
    },
    # -- Common --------------------------------------------------------
    "common.topics_only": {"ru": "⚠ Только в топиках.", "en": "⚠ Topics only."},
    "common.not_authorized": {
        "ru": "You are not authorized to use this bot.",
        "en": "You are not authorized to use this bot.",
    },
    # -- Context-fill alert (session_monitor) --------------------------
    "ctx.alert": {
        "ru": "📈 Контекст: {k}k токенов (~{pct}% из 1M)",
        "en": "📈 Context: {k}k tokens (~{pct}% of 1M)",
    },
    # -- BotCommand descriptions (set_my_commands) ---------------------
    "cmd.start": {"ru": "обновить клавиатуру меню", "en": "refresh the menu keyboard"},
    "cmd.status": {
        "ru": "сервер, агенты, диск, RAM",
        "en": "server, agents, disk, RAM",
    },
    "cmd.commands": {
        "ru": "панель агента (терминал + действия)",
        "en": "agent panel (terminal + actions)",
    },
    "cmd.screenshot": {"ru": "то же что /commands", "en": "same as /commands"},
    "cmd.restart": {"ru": "перезапуск агента", "en": "restart the agent"},
    "cmd.esc": {
        "ru": "прервать агента (Esc + Ctrl+C)",
        "en": "interrupt agent (Esc + Ctrl+C)",
    },
    "cmd.kill": {"ru": "завершить сессию агента", "en": "end the agent session"},
    "cmd.voice": {"ru": "включить/выключить TTS", "en": "toggle TTS on/off"},
    "cmd.react": {
        "ru": "отметка 👀 о приёме сообщения: вкл/выкл",
        "en": "👀 message-received mark: on/off",
    },
    "cmd.diff": {
        "ru": "показывать правки картинкой: вкл/выкл",
        "en": "show edits as images: on/off",
    },
    "cmd.lang": {"ru": "язык интерфейса (ru/en)", "en": "interface language (ru/en)"},
    "cmd.remount": {"ru": "пересмонтировать Drive", "en": "remount Drive"},
    "cmd.menu": {"ru": "показать клавиатуру меню", "en": "show the menu keyboard"},
    "cmd.mount": {"ru": "смонтировать Drive", "en": "mount Drive"},
    "cmd.umount": {"ru": "размонтировать Drive", "en": "unmount Drive"},
}


# ---------------------------------------------------------------------------
# Migrated UI strings, merged from the per-module migration. Grouped by
# namespace (module that owns them). tr() falls back to ru, so any gap
# here degrades to Russian rather than crashing.
# ---------------------------------------------------------------------------
STRINGS.update(
    {
        # -- bot --
        "bot.agent_waiting_in_dialog": {
            "ru": "⚠️ Агент ждёт ответа в диалоге \\(фото выше\\)\\. Сначала выбери вариант кнопками ↑↓⏎, потом отправь сообщение ещё раз\\.",
            "en": "⚠️ The agent is waiting for a reply in the dialog \\(photo above\\)\\. First pick an option with the ↑↓⏎ buttons, then send your message again\\.",
        },
        "bot.no_free_text_option": {
            "ru": "⚠️ У этого вопроса от агента нет поля свободного ответа\\. Выбери вариант через ↑↓⏎ — открой 🛠 Команды\\.",
            "en": "⚠️ This question from the agent has no free text answer field\\. Pick an option with ↑↓⏎ — open 🛠 Commands\\.",
        },
        # -- cb --
        "cb.agent_busy_stop_first": {
            "ru": "Агент сейчас работает — сначала останови его (⎋), потом перезапускай",
            "en": "The agent is working right now — stop it first (⎋), then restart",
        },
        "cb.agent_header": {"ru": "👾 *Агент:* {name}", "en": "👾 *Agent:* {name}"},
        "cb.agent_unavailable": {"ru": "Агент недоступен", "en": "Agent unavailable"},
        "cb.cancelled": {"ru": "Отменено", "en": "Cancelled"},
        "cb.confirm_action": {"ru": "Подтверди действие", "en": "Confirm the action"},
        "cb.container_not_running": {
            "ru": "Контейнер не запущен",
            "en": "Container not running",
        },
        "cb.done": {"ru": "Готово", "en": "Done"},
        "cb.input_wiped": {"ru": "🧽 Набранный текст стёрт", "en": "🧽 Input cleared"},
        "cb.kill_failed": {
            "ru": "Не удалось завершить сессию",
            "en": "Couldn't end the session",
        },
        "cb.mode_cycled": {"ru": "🎯 Режим сменён", "en": "🎯 Mode switched"},
        "cb.new_session_toast": {"ru": "✨ Новая сессия…", "en": "✨ New session…"},
        "cb.refresh_failed": {"ru": "Не удалось обновить", "en": "Couldn't refresh"},
        "cb.refreshed": {"ru": "Обновил", "en": "Refreshed"},
        "cb.refreshing": {"ru": "Обновляю…", "en": "Refreshing…"},
        "cb.remounting_drive": {
            "ru": "🔧 Перемонтирую Drive…",
            "en": "🔧 Remounting Drive…",
        },
        "cb.remounting_drive_plain": {
            "ru": "Перемонтирую Drive…",
            "en": "Remounting Drive…",
        },
        "cb.restarting_toast": {"ru": "🔄 Перезапускаю…", "en": "🔄 Restarting…"},
        "cb.session_ended_docker": {
            "ru": "⏹ Сессия `{display}` завершена.\nПерезапустить — `/restart` или 🔄 Рестарт в панели агента.",
            "en": "⏹ Session `{display}` ended.\nRestart — `/restart` or 🔄 Restart in the agent panel.",
        },
        "cb.session_ended_tmux": {
            "ru": "⏹ Сессия `{display}` завершена, топик отвязан.",
            "en": "⏹ Session `{display}` ended, topic unbound.",
        },
        "cb.window_gone": {
            "ru": "Окно больше не существует",
            "en": "Window no longer exists",
        },
        # -- commands --
        "commands.agent_caption": {
            "ru": "👾 *Агент:* {name}",
            "en": "👾 *Agent:* {name}",
        },
        "commands.agent_killed": {
            "ru": "💀 Агент '{name}' убит.",
            "en": "💀 Agent '{name}' killed.",
        },
        "commands.agent_not_configured": {
            "ru": "❌ Агент `{name}` не настроен. Известные: {available}",
            "en": "❌ Agent `{name}` is not configured. Known: {available}",
        },
        "commands.agent_not_found": {
            "ru": "❌ Агент '{name}' не найден.",
            "en": "❌ Agent '{name}' not found.",
        },
        "commands.agent_unavailable": {
            "ru": "❌ Агент '{name}' недоступен.",
            "en": "❌ Agent '{name}' unavailable.",
        },
        "commands.autobind_docker": {
            "ru": "✅ Топик авто\\-привязан к агенту `{name}` \\(docker\\)\\.",
            "en": "✅ Topic auto\\-bound to agent `{name}` \\(docker\\)\\.",
        },
        "commands.autobind_new_session": {
            "ru": "✅ Папка `{dir}` — новая сессия создана\\.",
            "en": "✅ Folder `{dir}` — new session created\\.",
        },
        "commands.autobind_resumed": {
            "ru": "✅ Папка `{dir}` — продолжаю прошлый разговор\\.",
            "en": "✅ Folder `{dir}` — resuming the last session\\.",
        },
        "commands.autobind_window_failed": {
            "ru": "❌ Не удалось создать окно для `{dir}`: {err}",
            "en": "❌ Failed to create a window for `{dir}`: {err}",
        },
        "commands.bind_done": {
            "ru": "✅ Топик привязан к агенту `{name}` (docker).",
            "en": "✅ Topic bound to agent `{name}` (docker).",
        },
        "commands.bind_usage": {
            "ru": "ℹ Использование: `/bind <agent>`\nДоступные агенты смотри в конфиге DOCKER\\_AGENTS.",
            "en": "ℹ Usage: `/bind <agent>`\nSee available agents in the DOCKER\\_AGENTS config.",
        },
        "commands.btn_clear": {"ru": "🧹 Очистить", "en": "🧹 Clear"},
        "commands.btn_compact": {"ru": "🗜 Сжать", "en": "🗜 Compact"},
        "commands.btn_context": {"ru": "📊 Контекст", "en": "📊 Context"},
        "commands.btn_delete_agent": {"ru": "🗑 Удалить агента", "en": "🗑 Delete agent"},
        "commands.btn_effort": {"ru": "⚡ Усилие", "en": "⚡ Effort"},
        "commands.btn_end": {"ru": "⏹ Завершить", "en": "⏹ End"},
        "commands.btn_mode": {"ru": "🎯 Режим", "en": "🎯 Mode"},
        "commands.btn_model": {"ru": "🤖 Модель", "en": "🤖 Model"},
        "commands.btn_new": {"ru": "🆕 Новая", "en": "🆕 New"},
        "commands.btn_new_worktree": {
            "ru": "🌳 Новый агент в проекте",
            "en": "🌳 New agent in project",
        },
        "commands.btn_restart": {"ru": "🔄 Перезапуск", "en": "🔄 Restart"},
        "commands.btn_resume": {"ru": "⏪ Продолжить", "en": "⏪ Resume"},
        "commands.btn_wipe_input": {"ru": "🧽 Стереть ввод", "en": "🧽 Wipe input"},
        "commands.cancel": {"ru": "↩ Отмена", "en": "↩ Cancel"},
        "commands.confirm_clear_btn": {"ru": "🧹 Да, очистить", "en": "🧹 Yes, clear"},
        "commands.confirm_clear_desc": {
            "ru": "🧹 Очистить контекст — агент забудет весь текущий диалог и начнёт с чистого листа.",
            "en": "🧹 Clear context — the agent forgets the whole current dialog and starts from a clean slate.",
        },
        "commands.confirm_compact_btn": {"ru": "🗜 Да, сжать", "en": "🗜 Yes, compact"},
        "commands.confirm_compact_desc": {
            "ru": "🗜 Сжать контекст — агент ужмёт историю диалога, чтобы освободить место. Сам диалог продолжится.",
            "en": "🗜 Compact context — the agent shrinks the dialog history to free up space. The dialog itself continues.",
        },
        "commands.confirm_default_btn": {"ru": "⚠️ Подтвердить", "en": "⚠️ Confirm"},
        "commands.confirm_fresh_btn": {
            "ru": "🆕 Да, начать заново",
            "en": "🆕 Yes, start over",
        },
        "commands.confirm_fresh_desc": {
            "ru": "🆕 Начать с нуля — запустится новый чистый диалог. Старый останется в списке Resume.",
            "en": "🆕 Start from scratch — a new clean dialog starts. The old one stays in the Resume list.",
        },
        "commands.confirm_kill_btn": {"ru": "⏹ Да, завершить", "en": "⏹ Yes, end"},
        "commands.confirm_kill_desc": {
            "ru": "⏹ Завершить сессию — агент остановится, текущая работа прервётся.",
            "en": "⏹ End session — the agent stops, the current work is interrupted.",
        },
        "commands.confirm_restart_btn": {
            "ru": "🔄 Да, перезапустить",
            "en": "🔄 Yes, restart",
        },
        "commands.confirm_restart_desc": {
            "ru": "🔄 Перезапустить — агент перезапустится и продолжит этот же диалог.",
            "en": "🔄 Restart — the agent restarts and continues this same dialog.",
        },
        "commands.container_not_running": {
            "ru": "❌ Контейнер не запущен.",
            "en": "❌ The container is not running.",
        },
        "commands.cron_boot": {"ru": " 🚀 при старте", "en": " 🚀 at boot"},
        "commands.cron_daily": {"ru": " ⏰ ежедневно", "en": " ⏰ daily"},
        "commands.cron_interval": {
            "ru": " ⏰ каждые N мин/ч",
            "en": " ⏰ every N min/h",
        },
        "commands.cron_weekly": {
            "ru": " ⏰ еженедельно ({wd})",
            "en": " ⏰ weekly ({wd})",
        },
        "commands.diff_off": {
            "ru": "✏️ Показ правок выключен\\.",
            "en": "✏️ Edit display off\\.",
        },
        "commands.diff_on": {
            "ru": "✏️ Показ правок включён\\.\nКогда агент правит файл, пришлю скриншот изменений из терминала \\(красным — убрано, зелёным — добавлено\\), на каждую правку\\.",
            "en": "✏️ Edit display on\\.\nWhen the agent edits a file, I'll send a screenshot of the changes from the terminal \\(red — removed, green — added\\), for every edit\\.",
        },
        "commands.docker_disabled": {
            "ru": "❌ Docker\\-агенты выключены в конфиге.",
            "en": "❌ Docker agents are disabled in the config.",
        },
        "commands.interrupted": {
            "ru": "⛔ Прервано (Escape + Ctrl+C)",
            "en": "⛔ Interrupted (Escape + Ctrl+C)",
        },
        "commands.mount_already": {
            "ru": "  🟢 {name} — уже смонтирован",
            "en": "  🟢 {name} — already mounted",
        },
        "commands.mount_error": {
            "ru": "  ❌ {name} — ошибка: {err}",
            "en": "  ❌ {name} — error: {err}",
        },
        "commands.mount_mounted": {
            "ru": "  ✅ {name} — смонтирован",
            "en": "  ✅ {name} — mounted",
        },
        "commands.mount_started": {
            "ru": "  ⏳ {name} — запущен, проверь /status",
            "en": "  ⏳ {name} — started, check /status",
        },
        "commands.mount_none": {
            "ru": "🗄 Нет настроенных rclone-маунтов (задай `CCBOT_RCLONE_MOUNTS` в `.env`).",
            "en": "🗄 No rclone mounts configured (set `CCBOT_RCLONE_MOUNTS` in `.env`).",
        },
        "commands.no_session_in_topic": {
            "ru": "❌ Нет сессии в этом топике.",
            "en": "❌ No session in this topic.",
        },
        "commands.none_paren": {"ru": "(нет)", "en": "(none)"},
        "commands.only_in_topic": {
            "ru": "❌ Только в топике.",
            "en": "❌ Only in a topic.",
        },
        "commands.react_off": {
            "ru": "👀 Отметка о приёме выключена\\.",
            "en": "👀 Receipt mark off\\.",
        },
        "commands.react_on": {
            "ru": "👀 Отметка о приёме включена\\.\nБот поставит 👀 на твоё сообщение, когда агент возьмёт его в работу\\.\nЧтобы без пуша — отключи уведомления о реакциях в настройках Telegram\\.",
            "en": "👀 Receipt mark on\\.\nThe bot will put 👀 on your message once the agent picks it up\\.\nTo silence the push — turn off reaction notifications in Telegram settings\\.",
        },
        "commands.refresh": {"ru": "📸 Обновить", "en": "📸 Refresh"},
        "commands.remount_docker_restarted": {
            "ru": "  ✅ docker {name} — перезапущен",
            "en": "  ✅ docker {name} — restarted",
        },
        "commands.remount_docker_timeout": {
            "ru": "  ❌ docker {name} — timeout на restart",
            "en": "  ❌ docker {name} — restart timeout",
        },
        "commands.remount_done": {
            "ru": "  ✅ {remote} — пересмонтирован",
            "en": "  ✅ {remote} — remounted",
        },
        "commands.remount_failed": {
            "ru": "  ❌ {remote} — не смонтировался, проверь логи",
            "en": "  ❌ {remote} — failed to mount, check logs",
        },
        "commands.restart_busy": {
            "ru": "⚠️ {name} сейчас работает — перезапуск отправил бы команды ему в строку ввода. Останови его (⎋ в панели 👾 Агент), потом перезапускай.",
            "en": "⚠️ {name} is working right now — a restart would type the commands into its input line. Stop it (⎋ in the 👾 Agent panel), then restart.",
        },
        "commands.restart_maybe_failed": {
            "ru": "⚠️ {name} возможно не запустился. Проверь /screenshot.",
            "en": "⚠️ {name} may not have started. Check /screenshot.",
        },
        "commands.restart_no_tmux": {
            "ru": "⚠️ {name}: не удалось создать tmux-сессию в контейнере.",
            "en": "⚠️ {name}: failed to create a tmux session in the container.",
        },
        "commands.restarted": {
            "ru": "✅ {name} перезапущен.",
            "en": "✅ {name} restarted.",
        },
        "commands.restarting": {
            "ru": "🔄 Перезапускаю {name}...",
            "en": "🔄 Restarting {name}...",
        },
        "commands.status_agents": {
            "ru": "🤖 Агенты · {alive}/{total}",
            "en": "🤖 Agents · {alive}/{total}",
        },
        "commands.status_all_ok": {"ru": "всё ок", "en": "all OK"},
        "commands.status_background": {
            "ru": "⚙️ Фоновые · {n}/{n}",
            "en": "⚙️ Background · {n}/{n}",
        },
        "commands.status_disk": {"ru": "Диск", "en": "Disk"},
        "commands.status_fix_drive": {"ru": "🔧 Починить Drive", "en": "🔧 Fix Drive"},
        "commands.status_header": {
            "ru": "📊 Статус сервера · {summary}",
            "en": "📊 Server status · {summary}",
        },
        "commands.status_mount_down": {
            "ru": "🔴 {name} (не смонтирован/завис)",
            "en": "🔴 {name} (not mounted/hung)",
        },
        "commands.status_mount_error": {
            "ru": "🔴 {name} (ошибка)",
            "en": "🔴 {name} (error)",
        },
        "commands.status_mounts": {
            "ru": "📦 Маунты · {ok}/{total}",
            "en": "📦 Mounts · {ok}/{total}",
        },
        "commands.status_n_tasks": {
            "ru": "{name} — {n} задач",
            "en": "{name} — {n} tasks",
        },
        "commands.status_not_started": {"ru": "не запущен", "en": "not running"},
        "commands.status_refresh": {"ru": "🔄 Обновить", "en": "🔄 Refresh"},
        "commands.status_resources": {"ru": "💾 Ресурсы", "en": "💾 Resources"},
        "commands.status_schedule": {
            "ru": "⏰ Расписание · {emoji} {n} задач\n",
            "en": "⏰ Schedule · {emoji} {n} tasks\n",
        },
        "commands.status_stopped": {"ru": "остановлен", "en": "stopped"},
        "commands.status_warnings": {"ru": "⚠️ {n} предупр.", "en": "⚠️ {n} warnings"},
        "commands.tab_act": {"ru": "🛠 Действия", "en": "🛠 Actions"},
        "commands.tab_nav": {"ru": "⌨️ Навигация", "en": "⌨️ Navigation"},
        "commands.umount_not_mounted": {
            "ru": "  ⚪ {name} — не смонтирован",
            "en": "  ⚪ {name} — not mounted",
        },
        "commands.umount_unmounted": {
            "ru": "  ✅ {name} — размонтирован",
            "en": "  ✅ {name} — unmounted",
        },
        "commands.uptime_days": {"ru": "{n} дн.", "en": "{n}d"},
        "commands.uptime_hours": {"ru": "{n} ч.", "en": "{n}h"},
        "commands.uptime_mins": {"ru": "{n} мин.", "en": "{n}m"},
        "commands.voice_no_provider": {
            "ru": "⚠ Нет сконфигурированного TTS\\-провайдера\\. Задай GEMINI\\_API\\_KEY \\(или ELEVENLABS\\_\\*, или OPENAI\\_API\\_KEY\\) в \\.env, опционально TTS\\_PROVIDER для выбора конкретного\\.",
            "en": "⚠ No TTS provider configured\\. Set GEMINI\\_API\\_KEY \\(or ELEVENLABS\\_\\*, or OPENAI\\_API\\_KEY\\) in \\.env, optionally TTS\\_PROVIDER to pick a specific one\\.",
        },
        "commands.voice_off": {
            "ru": "🔇 Голосовой режим выключен",
            "en": "🔇 Voice mode off",
        },
        "commands.voice_on": {
            "ru": "🔊 Голосовой режим включён",
            "en": "🔊 Voice mode on",
        },
        "commands.window_gone": {
            "ru": "❌ Окно '{name}' больше нет.",
            "en": "❌ Window '{name}' no longer exists.",
        },
        "commands.window_not_exist": {
            "ru": "❌ Окно '{name}' не существует.",
            "en": "❌ Window '{name}' does not exist.",
        },
        # -- ctxp --
        "ctxp.categories": {"ru": "Категории:", "en": "Categories:"},
        # -- dirb --
        "dirb.change_folder": {"ru": "📂 Сменить папку", "en": "📂 Change folder"},
        # -- iui --
        "iui.btn_open_login": {"ru": "🔗 Открыть вход", "en": "🔗 Open sign-in"},
        "iui.btn_refresh": {"ru": "🔄 Обновить", "en": "🔄 Refresh"},
        "iui.caption_waiting": {
            "ru": "❓ *Claude ждёт ответа*",
            "en": "❓ *Claude is waiting for a reply*",
        },
        "iui.login_prompt": {
            "ru": "🔐 *Вход в Claude*\n\nОткрой ссылку, войди в аккаунт, потом пришли сюда код, если попросит.\n\n`{url}`",
            "en": "🔐 *Sign in to Claude*\n\nOpen the link, sign in to your account, then send the code here if asked.\n\n`{url}`",
        },
        # -- lboard --
        "lboard.header": {
            "ru": "📡 <b>Поднято сейчас</b> · обновлено {time}\n\n{body}",
            "en": "📡 <b>Up right now</b> · updated {time}\n\n{body}",
        },
        "lboard.nothing_up": {
            "ru": "Сейчас ничего не поднято.",
            "en": "Nothing is up right now.",
        },
        "lboard.section_apps": {
            "ru": "🔗 Постоянные app-хосты",
            "en": "🔗 Permanent app hosts",
        },
        "lboard.section_previews": {
            "ru": "🌐 Preview-серверы",
            "en": "🌐 Preview servers",
        },
        # -- links --
        "links.header": {"ru": "🔗 Ссылки", "en": "🔗 Links"},
        "links.overflow": {"ru": "… и ещё {extra}", "en": "… and {extra} more"},
        # -- media --
        "media.archive_sent": {
            "ru": "📦 Архив «{name}» отправлен агенту — попросил его распаковать.",
            "en": "📦 Archive «{name}» sent to the agent — asked it to unpack it.",
        },
        "media.download_failed": {
            "ru": "❌ Не смог скачать файл из Telegram.",
            "en": "❌ Couldn't download the file from Telegram.",
        },
        "media.download_failed_too_big": {
            "ru": " Похоже, он больше 20 МБ — разбей архив на части или пришли файлы по отдельности.",
            "en": " Looks like it's over 20 MB — split the archive into parts or send the files separately.",
        },
        "media.file_too_big": {
            "ru": "❌ Файл слишком большой (~{mb} МБ). Telegram разрешает боту скачивать файлы только до 20 МБ — это ограничение Telegram, не бота.\n\nРазбей архив на части по ≤20 МБ или пришли файлы по отдельности.",
            "en": "❌ File too large (~{mb} MB). Telegram only lets a bot download files up to 20 MB — that's a Telegram limit, not the bot's.\n\nSplit the archive into ≤20 MB parts or send the files separately.",
        },
        "media.voice_blocked_no_text_option": {
            "ru": '🎤 "{text}"\n\n⚠️ У вопроса агента нет поля свободного ответа — выбери вариант через ↑↓⏎ в панели 👾 Агент\\.',
            "en": '🎤 "{text}"\n\n⚠️ The agent\'s question has no free text field — pick an option with ↑↓⏎ in the 👾 Agent panel\\.',
        },
        "media.voice_blocked_widget": {
            "ru": '🎤 "{text}"\n\n⚠️ Агент ждёт ответа в диалоге\\. Сначала выбери вариант кнопками ↑↓⏎, потом надиктуй ещё раз\\.',
            "en": '🎤 "{text}"\n\n⚠️ The agent is waiting for a reply in the dialog\\. First pick an option with the ↑↓⏎ buttons, then dictate again\\.',
        },
        # -- mq --
        "mq.agent_looking": {"ru": "👀 Агент смотрит", "en": "👀 Agent is looking"},
        "mq.code_file_caption": {
            "ru": "📄 {filename} ({n_lines} строк)",
            "en": "📄 {filename} ({n_lines} lines)",
        },
        "mq.diff_changes": {"ru": "✏️ Изменения", "en": "✏️ Changes"},
        "mq.voice_budget_warning": {
            "ru": "🔊 Голос: {used}/{limit} симв. за сегодня (80% дневного лимита). Осталось ≈{remaining} симв.",
            "en": "🔊 Voice: {used}/{limit} chars today (80% of daily limit). ≈{remaining} chars left.",
        },
        "mq.voice_exhausted_summary": {
            "ru": "🔇 Голос выключен во всех топиках — превышен дневной лимит ({used}/{limit} симв.). Сброс в 00:00.",
            "en": "🔇 Voice turned off in all topics — daily limit exceeded ({used}/{limit} chars). Resets at 00:00.",
        },
        "mq.voice_exhausted_topic": {
            "ru": "🔇 Голос автоматически выключен — превышен дневной лимит TTS. Сбросится в 00:00. Возобновить: /voice",
            "en": "🔇 Voice turned off automatically — daily TTS limit exceeded. Resets at 00:00. Resume: /voice",
        },
        # -- rconf --
        "rconf.agent_busy": {
            "ru": "👍 — но агент сейчас занят, ничего не отправляю. Ответь словом, когда освободится.",
            "en": "👍 — but the agent is busy right now, not sending anything. Reply with a word when it's free.",
        },
        "rconf.confirmed": {"ru": "👍 — подтвердил", "en": "👍 — confirmed"},
        "rconf.sent_yes": {
            "ru": "👍 — отправил агенту «да»",
            "en": "👍 — sent «yes» to the agent",
        },
        # -- spoll --
        "spoll.agent_stopped": {
            "ru": "⚠️ Агент *{name}* остановлен. Окно будет закрыто через {grace}с. Используй /restart чтобы перезапустить.",
            "en": "⚠️ Agent *{name}* stopped. The window will be closed in {grace}s. Use /restart to restart it.",
        },
        "spoll.window_closed": {
            "ru": "💀 Окно *{name}* закрыто (агент не работал {secs}с).",
            "en": "💀 Window *{name}* closed (the agent was down for {secs}s).",
        },
        "spoll.model_switched": {
            "ru": "⚠️ Сработал предохранитель модели на последнее сообщение — агент сам переключился на {model}. Сейчас предохранители широкие и могут срабатывать даже на безопасные задачи (код, кибербезопасность, биология).",
            "en": "⚠️ A model safeguard fired on the last message — the agent auto-switched to {model}. Safeguards are broad right now and can trip even on safe work (coding, cybersecurity, biology).",
        },
        "spoll.model_switched_fallback": {
            "ru": "другую модель",
            "en": "another model",
        },
        # -- wt --
        "wt.agent_deleted": {
            "ru": "🗑 Агент «{title}» удалён.",
            "en": "🗑 Agent «{title}» deleted.",
        },
        "wt.agent_gone": {"ru": "Агента уже нет", "en": "The agent is already gone"},
        "wt.bits_ahead": {
            "ru": "{count} невлитых коммитов",
            "en": "{count} unmerged commits",
        },
        "wt.bits_dirty": {
            "ru": "{count} несохранённых файлов",
            "en": "{count} unsaved files",
        },
        "wt.bullet_ahead": {
            "ru": "• {count} коммит(ов) не в {base}",
            "en": "• {count} commit(s) not in {base}",
        },
        "wt.bullet_dirty": {
            "ru": "• {count} файл(а/ов) с несохранёнными правками",
            "en": "• {count} file(s) with unsaved edits",
        },
        "wt.cancel": {"ru": "↩ Отмена", "en": "↩ Cancel"},
        "wt.cancelled": {"ru": "Отменено", "en": "Cancelled"},
        "wt.close_guard_footer": {
            "ru": "\n\nРабочая копия цела. Что делаем?",
            "en": "\n\nThe working copy is intact. What do we do?",
        },
        "wt.close_guard_header": {
            "ru": "⚠️ Не закрываю «{title}» — есть невлитая работа:\n",
            "en": "⚠️ Not closing «{title}» — there's unmerged work:\n",
        },
        "wt.copy_branch": {"ru": "📋 Ветка", "en": "📋 Branch"},
        "wt.copy_path": {"ru": "📋 Путь", "en": "📋 Path"},
        "wt.creating": {"ru": "⏳ Создаю агента…", "en": "⏳ Creating the agent…"},
        "wt.del_confirm_clean": {
            "ru": "🗑 Удалить агента «{title}»?\nВсё влито, терять нечего — снесу копию, ветку и топик.",
            "en": "🗑 Delete agent «{title}»?\nEverything is merged, nothing to lose — I'll remove the copy, branch and topic.",
        },
        "wt.del_confirm_dirty": {
            "ru": "⚠️ У «{title}» есть: {bits}.\nУдаление сотрёт это НАВСЕГДА.",
            "en": "⚠️ «{title}» has: {bits}.\nDeleting will erase this FOREVER.",
        },
        "wt.del_ok_clean": {"ru": "✅ Да, удалить", "en": "✅ Yes, delete"},
        "wt.del_ok_dirty": {
            "ru": "🧨 Удалить и потерять",
            "en": "🧨 Delete and lose it",
        },
        "wt.delete_anyway": {"ru": "🧨 Всё равно удалить", "en": "🧨 Delete anyway"},
        "wt.deleting": {"ru": "🗑 Удаляю…", "en": "🗑 Deleting…"},
        "wt.empty_name": {
            "ru": "Пустое имя — отменил.",
            "en": "Empty name — cancelled.",
        },
        "wt.err_no_base_branch": {
            "ru": "не определить базовую ветку (detached HEAD?)",
            "en": "couldn't determine the base branch (detached HEAD?)",
        },
        "wt.err_topic_not_created": {
            "ru": "топик не создан: {error}",
            "en": "topic not created: {error}",
        },
        "wt.err_window": {"ru": "окно: {error}", "en": "window: {error}"},
        "wt.keep_agent": {"ru": "↩ Оставить агента", "en": "↩ Keep the agent"},
        "wt.kept_msg": {
            "ru": "↩ Оставил — агент на месте.",
            "en": "↩ Kept — the agent is still here.",
        },
        "wt.kept_toast": {"ru": "↩ Оставил", "en": "↩ Kept"},
        "wt.new_agent_prompt": {
            "ru": "🌱 Новый агент в проекте {repo}.\nНапиши коротко, как назвать задачу — например «редизайн шапки». Это станет именем топика и ветки; задачу поставишь уже в новом топике.",
            "en": "🌱 New agent in project {repo}.\nWrite a short name for the task — for example «header redesign». It becomes the topic and branch name; you'll set the actual task in the new topic.",
        },
        "wt.no_project": {
            "ru": "Не определить проект этого топика",
            "en": "Can't determine this topic's project",
        },
        "wt.not_git_repo": {
            "ru": "{repo} — не git-репозиторий",
            "en": "{repo} — not a git repository",
        },
        "wt.not_in_topic": {"ru": "Не в топике", "en": "Not in a topic"},
        "wt.not_worktree_agent": {
            "ru": "Это не worktree-агент",
            "en": "This isn't a worktree agent",
        },
        "wt.panel_agent_header": {
            "ru": "👾 *Агент:* {name}",
            "en": "👾 *Agent:* {name}",
        },
        "wt.provision_failed": {
            "ru": "❌ Не удалось: {info}",
            "en": "❌ Failed: {info}",
        },
        "wt.provision_ok": {
            "ru": "Агент создан: 🌳 {repo} · {title} (ветка {branch})",
            "en": "Agent created: 🌳 {repo} · {title} (branch {branch})",
        },
        "wt.welcome": {
            "ru": "🌳 Готово — параллельный агент проекта {repo}.\nВетка: {branch} (отдельная копия, в main сам не вливаю).\n\nПиши задачу 👇",
            "en": "🌳 Done — a parallel agent for project {repo}.\nBranch: {branch} (a separate copy, I don't merge it into main myself).\n\nWrite the task 👇",
        },
    }
)
