"""UI-string catalog for ccbot's user-facing text.

ccbot's chrome — buttons, status lines, error messages, /command
descriptions, dashboards, notifications — is English, and every string
lives in the catalog below rather than inline at the call site: one place
to read the whole voice of the bot, and one place to edit it. Call sites
just call `tr("some.key")`.

Scope: only ccbot's OWN strings. The agent's replies (generated by
Claude Code, merely relayed) and agent-directed text (voice protocol
directives) are NOT translated here.

`STRINGS[key] = "text"`. `tr` falls back to the key itself, so a missing
entry is visible in the UI rather than a crash.

Key naming: dotted, namespaced by area (`menu.server`, `cmd.status`,
`ctx.alert`, `panel.refresh`, …) so additions
from different modules never collide.
"""


def register(strings: dict[str, str]) -> None:
    """Merge plugin-contributed catalog entries into ``STRINGS``.

    Lets an optional plugin own its user-facing strings (namespaced by area)
    without the core catalog naming the plugin. Called once at startup by
    ``plugins.register_i18n``; last writer wins on a key clash.
    """
    STRINGS.update(strings)


def tr(key: str, /, **fmt: object) -> str:
    """Look `key` up in the catalog, then `str.format(**fmt)`.

    An unknown key returns the key itself (visible, never a crash), and a
    `.format` that raises on a bad placeholder returns the unformatted text
    rather than propagating — a UI string is never worth a 500.
    """
    text = STRINGS.get(key)
    if text is None:
        return key
    if fmt:
        try:
            return text.format(**fmt)
        except (KeyError, IndexError, ValueError):
            return text
    return text


# ---------------------------------------------------------------------------
# Catalog. Infra strings are seeded here; per-module UI strings are appended
# below (one block per source module) as the migration proceeds. Keep blocks
# grouped by namespace so it's obvious which module owns which keys.
# ---------------------------------------------------------------------------
STRINGS: dict[str, str] = {
    # -- Persistent menu (ReplyKeyboard) --------------------------------
    "menu.server": "🖥️ Server",
    "menu.agent": "👾 Agent",
    "menu.pinned": "👾 Menu pinned",
    # -- Common --------------------------------------------------------
    "common.topics_only": "⚠ Topics only.",
    # Shown to strangers AND to the owner with a misconfigured ALLOWED_USERS —
    # the id in the text lets the owner fix .env without hunting for
    # @userinfobot (the most common friend-install failure).
    "common.not_authorized": "⛔ Access not configured. Your Telegram id: {uid} — if this is your bot, add the id to ALLOWED_USERS in .env and restart the bot.",
    # The anonymous-admin service id gets its own advice: the generic «add it
    # to ALLOWED_USERS» is the classic WRONG fix for it (access "works", but
    # the service id forks into its own binding universe — the owner's topics
    # start offering fresh sessions).
    "common.not_authorized_anon": "⛔ This message came via anonymous-admin mode: id {uid} is the @GroupAnonymousBot service account, not your own — don't add it to ALLOWED_USERS. Turn off «Remain anonymous» in your group admin rights — or allow anonymous posts with CCBOT_USER_ALIASES={uid}:<your id> in .env and restart the bot.",
    # -- Context-fill alert (session_monitor) --------------------------
    "ctx.alert": "📈 Context: {k}k tokens (~{pct}% of 1M)",
    # -- BotCommand descriptions (set_my_commands) ---------------------
    "cmd.start": "getting started & setup check",
    "cmd.help": "what this bot can do",
    "cmd.status": "server, agents, disk, RAM",
    "cmd.commands": "agent panel (terminal + actions)",
    "cmd.screenshot": "same as /commands",
    "cmd.restart": "restart the agent",
    "cmd.esc": "interrupt agent (Esc + Ctrl+C)",
    "cmd.kill": "end the agent session",
    "cmd.voice": "toggle TTS on/off",
    "cmd.react": "👀 message-received mark: on/off",
    "cmd.tables": "tables: native or screenshots",
    "cmd.diff": "show edits as images: on/off",
    "cmd.pin": "pin big task messages: on/off",
    "cmd.menu": "show the menu keyboard",
}


# ---------------------------------------------------------------------------
# Migrated UI strings, merged from the per-module migration. Grouped by
# namespace (module that owns them). tr() falls back to ru, so any gap
# here degrades to Russian rather than crashing.
# ---------------------------------------------------------------------------
STRINGS.update(
    {
        # -- bot --
        "bot.use_picker_above": "⬆️ Please use the picker above, or tap Cancel.",
        "bot.use_named_topic": "❌ Please write in a named topic: one topic is one session. Create a new topic to start.",
        "bot.private_start": "👋 I bridge Telegram and terminal AI agents (Claude Code, Codex, …), and I work in a group with topics.\n\n1. Create a group and enable *Topics* in its settings.\n2. Add me to the group and make me an admin.\n3. Create a topic named after a project folder — and just write.\n\nFull walkthrough — SETUP.md in the repository.",
        "bot.help": "🤖 *How I work*\n"
        "One topic = one terminal agent: Claude Code, Codex — the session picker has a tab per installed CLI, with more runtimes to come. Create a topic (name it after a project folder — it binds itself), send a message — it goes to the agent, and its replies come back here.\n\n"
        "*Bottom buttons:* 🖥️ Server — server summary · 👾 Agent — control panel (live terminal screenshot, keys, mode, model, restart…).\n\n"
        "*Toggles:*\n"
        "/voice — spoken replies (needs a TTS key)\n"
        "/diff — send screenshots of code edits\n"
        "/tables — tables: native or screenshots\n"
        "/pin — pin big task messages in the topic\n"
        "/react — 👀 “message taken” receipt\n\n"
        "*Good to know:*\n"
        "• 👍 on an agent message = confirm (Enter or “yes”)\n"
        "• Photos, files and voice messages reach the agent too\n"
        "• Unknown /commands (/clear, /compact, /review…) go straight to the agent\n"
        "• 🌳 in the panel — a parallel agent in a git worktree\n"
        "• Closing a topic ends its session\n\n"
        "*If the agent is silent:* check the hook (`uv run ccbot hook --install` on the server), then /status and the 👾 Agent panel → 📸.",
        "bot.enable_topics_hint": "⚠️ Topics are not enabled in this group, and I can't work without them. Group settings → Topics → enable, then create a topic.",
        "bot.make_me_admin": "⚠️ Make me a group administrator — without admin rights Telegram doesn't deliver regular messages to me, so I can't respond.\nGroup settings → Administrators → Add administrator.",
        "bot.docker_agent_down": "❌ Docker agent `{name}` is not running; binding removed.\nRun `/bind {name}` once the container is up.",
        "bot.window_gone": "❌ Window `{name}` no longer exists; binding removed.\nSend a message to start a new session.",
        "bot.window_ready": "✅ New session in `{dir}`. Messages here go straight to the agent.",
        "bot.window_resumed": "✅ Resumed the last session in `{dir}`. Messages here go straight to the agent.",
        "bot.window_codex_ready": "✅ Codex started in `{dir}`. If sign-in is needed, a menu with "
        "nav buttons (↑ ↓ ⏎) will pop up shortly — pick “Sign in with "
        "Device Code”; I'll post the sign-in link as a separate message.",
        "runtime.version_changed": "⚠️ {agent} updated itself: {old} → {new}.\n"
        "The bot's screen parsing is pinned to the previous version. "
        "If anything looks off (agent seems stuck, empty Context, "
        "broken edit screenshots) — restart the session and re-verify "
        "the screen parsing.",
        "bot.same_dir_conflict": "⚠️ A {agent} agent from another topic is already running in "
        "`{dir}`. {agent} can't keep two sessions in one folder apart — "
        "replies would cross between topics. Continue in that topic or "
        "pick a different folder.",
        "bot.bound_to_window": "✅ Bound to window `{name}`.",
        "bot.pending_send_failed": "❌ Failed to forward your message to the agent: {err}",
        "bot.send_file_missing": "📎 The agent meant to send a file, but there is nothing at `{path}` — no attachment was sent. Ask it to save the file again and resend.",
        "bot.send_file_rejected": "📎 The agent tried to send a file from outside its workspace (`{path}`) — no attachment was sent. Only /workspace is allowed.",
        "bot.hook_missing": "⚠️ The session-tracking hook is not installed — the agent's replies will NOT reach this chat.\nOn the server run: `uv run ccbot hook --install`, then restart the agent.",
        "bot.start_welcome": "🤖 *Your terminal agents in Telegram*\n\nEach topic is one agent (Claude Code, Codex, …). Create a new topic to start.",
        "bot.agent_waiting_in_dialog": "⚠️ The agent is waiting for a reply in the dialog \\(photo above\\)\\. First pick an option with the ↑↓⏎ buttons, then send your message again\\.",
        "bot.pending_deferred": "⏳ The agent is waiting for an answer in the dialog first \\(photo above\\)\\. Pick an option with the ↑↓⏎ buttons — your message goes to it right after\\.",
        "bot.pending_undelivered": "⚠️ Your message never reached the agent — the dialog is still waiting for an answer\\. Answer it, then send the message again\\.",
        "bot.no_free_text_option": "⚠️ This question from the agent has no free text answer field\\. Pick an option with ↑↓⏎ — open 🛠 Commands\\.",
        # -- cb --
        "cb.agent_busy_stop_first": "The agent is working right now — stop it first (⎋), then restart",
        "cb.agent_header": "👾 *Agent:* {name}",
        "cb.agent_unavailable": "Agent unavailable",
        "cb.cancelled": "Cancelled",
        "cb.stale_panel": "This panel is stale and points at a different agent. Open a fresh one: 👾 Agent button.",
        "cb.confirm_action": "Confirm the action",
        "cb.container_not_running": "Container not running",
        "cb.done": "Done",
        "cb.failed": "Failed",
        "cb.invalid_data": "Invalid data",
        "cb.page_updated": "Page updated",
        "cb.list_changed": "List changed, please refresh",
        "cb.dir_not_found": "Directory not found",
        "cb.session_not_found": "Session not found",
        "cb.not_in_topic": "Not in a topic",
        "cb.bound": "Bound",
        "cb.unknown_key": "Unknown key",
        "cb.not_authorized_toast": "Not authorized",
        "cb.stale_ui": "These buttons belong to another topic",
        "cb.input_wiped": "🧽 Input cleared",
        "cb.kill_failed": "Couldn't end the session",
        "cb.mode_cycled": "🎯 Mode switched",
        "cb.new_session_toast": "✨ New session…",
        "cb.refresh_failed": "Couldn't refresh",
        "cb.refreshed": "Refreshed",
        "cb.refreshing": "Refreshing…",
        "cb.restarting_toast": "🔄 Restarting…",
        "cb.session_ended_docker": "⏹ Session `{display}` ended.\nRestart — `/restart` or 🔄 Restart in the agent panel.",
        "cb.session_ended_tmux": "⏹ Session `{display}` ended, topic unbound.",
        "cb.window_gone": "Window no longer exists",
        # -- commands --
        "commands.agent_caption": "👾 *Agent:* {name}",
        "commands.agent_killed": "💀 Agent '{name}' killed.",
        "commands.agent_not_configured": "❌ Agent `{name}` is not configured. Known: {available}",
        "commands.agent_not_found": "❌ Agent '{name}' not found.",
        "commands.agent_unavailable": "❌ Agent '{name}' unavailable.",
        "commands.autobind_docker": "✅ Topic auto\\-bound to agent `{name}` \\(docker\\)\\.",
        "commands.bind_done": "✅ Topic bound to agent `{name}` (docker).",
        "commands.bind_usage": "ℹ Usage: `/bind <agent>`\nSee available agents in the DOCKER\\_AGENTS config.",
        "commands.btn_clear": "🧹 Clear",
        "commands.btn_compact": "🗜 Compact",
        "commands.btn_context": "📊 Context",
        "commands.btn_delete_agent": "🗑 Delete agent",
        "commands.btn_effort": "⚡ Effort",
        "commands.btn_end": "⏹ End",
        "commands.btn_mode": "🎯 Mode",
        "commands.btn_model": "🤖 Model",
        "commands.btn_new": "🆕 New session",
        "commands.btn_new_worktree": "🌳 Worktree agent",
        "commands.btn_new_sibling": "➕ One more agent",
        "commands.btn_restart": "🔄 Restart",
        "commands.btn_resume": "⏪ Resume",
        "commands.btn_wipe_input": "🧽 Wipe input",
        "commands.cancel": "↩ Cancel",
        "commands.confirm_clear_btn": "🧹 Yes, clear",
        "commands.confirm_clear_desc": "🧹 Clear context — the agent forgets the whole current dialog and starts from a clean slate.",
        "commands.confirm_compact_btn": "🗜 Yes, compact",
        "commands.confirm_compact_desc": "🗜 Compact context — the agent shrinks the dialog history to free up space. The dialog itself continues.",
        "commands.confirm_default_btn": "⚠️ Confirm",
        "commands.confirm_fresh_btn": "🆕 Yes, start over",
        "commands.confirm_fresh_desc": "🆕 Start from scratch — a new clean dialog starts. The old one stays in the Resume list.",
        "commands.confirm_kill_btn": "⏹ Yes, end",
        "commands.confirm_kill_desc": "⏹ End session — the agent stops, the current work is interrupted.",
        "commands.confirm_restart_btn": "🔄 Yes, restart",
        "commands.confirm_restart_desc": "🔄 Restart — the agent restarts and continues this same dialog.",
        "commands.container_not_running": "❌ The container is not running.",
        "commands.cron_boot": " 🚀 at boot",
        "commands.cron_label_min": "{n}m",
        "commands.cron_label_hourly": "1h (:{mm})",
        "commands.cron_label_every_h": "{t1},{t2}… (every {n}h)",
        "commands.cron_stopped": "cron is stopped",
        "commands.cron_wd_0": "Mon",
        "commands.cron_wd_1": "Tue",
        "commands.cron_wd_2": "Wed",
        "commands.cron_wd_3": "Thu",
        "commands.cron_wd_4": "Fri",
        "commands.cron_wd_5": "Sat",
        "commands.cron_wd_6": "Sun",
        "commands.cron_daily": " ⏰ daily",
        "commands.cron_interval": " ⏰ every N min/h",
        "commands.cron_weekly": " ⏰ weekly ({wd})",
        "commands.diff_off": "✏️ Edit display off\\.",
        "commands.diff_on": "✏️ Edit display on\\.\nWhen the agent edits a file, I'll send a screenshot of the changes from the terminal \\(red — removed, green — added\\), for every edit\\.",
        "commands.docker_disabled": "❌ Docker agents are disabled in the config.",
        "commands.interrupted": "⛔ Interrupted (Escape + Ctrl+C)",
        "commands.no_session_in_topic": "❌ No session in this topic. Send any message and I'll offer to pick a folder and start an agent.",
        "commands.none_paren": "(none)",
        "commands.only_in_topic": "❌ Only in a topic.",
        # NB: no hand-written MarkdownV2 escapes here — these strings go
        # through convert_markdown (telegramify), which does the escaping
        # itself and treats `\(...\)` as inline LaTeX math (renders the body
        # as code and eats the parens — bit the en string once).
        "commands.pin_off": "📌 Task pinning off.",
        "commands.pin_on": "📌 Task pinning on.\nBig messages ({n}+ characters) sent to an idle agent get pinned — the pinned list becomes this topic's task history. Short replies and mid-work follow-ups are not pinned.",
        "commands.react_off": "👀 Receipt mark off\\.",
        "commands.react_on": "👀 Receipt mark on\\.\nThe bot will put 👀 on your message once the agent picks it up\\.\nTo silence the push — turn off reaction notifications in Telegram settings\\.",
        "commands.refresh": "📸 Refresh",
        "commands.tables_rich": "📊 Tables are now native — Telegram draws them, text is selectable and copyable\\.\nSend /tables again to switch back to screenshots\\.",
        "commands.tables_image": "🖼 Tables now arrive as grid screenshots\\.\nSend /tables again to switch back to native tables\\.",
        "commands.restart_busy": "⚠️ {name} is working right now — a restart would type the commands into its input line. Stop it (⎋ in the 👾 Agent panel), then restart.",
        "commands.restart_maybe_failed": "⚠️ {name} may not have started. Check /screenshot.",
        "commands.restart_no_tmux": "⚠️ {name}: failed to create a tmux session in the container.",
        "commands.restarted": "✅ {name} restarted.",
        "restart.nothing_to_revive": "❌ Nothing to bring back here — this topic has no folder yet. Send a message to pick one.",
        "restart.window_failed": "❌ Couldn't start the agent again: {err}",
        "restart.revived": "🔄 {name} is back — same folder, same conversation.",
        "cb.reviving_toast": "🔄 Bringing the agent back…",
        "commands.restarting": "🔄 Restarting {name}...",
        "commands.status_agents": "🤖 Agents · {alive}/{total}",
        "commands.status_all_ok": "all OK",
        "commands.status_background": "⚙️ Background · {n}/{n}",
        "commands.status_disk": "Disk",
        "commands.status_header": "📊 Server status · {summary}",
        "commands.status_n_tasks": "{name} — {n} tasks",
        "commands.status_not_started": "not running",
        "commands.status_refresh": "🔄 Refresh",
        "commands.status_resources": "💾 Resources",
        "commands.status_schedule": "⏰ Schedule · {emoji} {n} tasks\n",
        "commands.status_stopped": "stopped",
        "commands.status_warn_agent": "agent {name}",
        "commands.status_warn_disk": "disk {pct}%",
        "commands.status_warn_ram": "RAM {pct}%",
        "commands.status_warnings": "⚠️ {n} warnings",
        "commands.tab_act": "🛠 Actions",
        "commands.tab_nav": "⌨️ Keys",
        "commands.tab_ses": "⚙️ Session",
        "commands.uptime_days": "{n}d",
        "commands.uptime_hours": "{n}h",
        "commands.uptime_mins": "{n}m",
        "commands.voice_no_provider": "⚠ No TTS provider configured\\. Set GEMINI\\_API\\_KEY \\(or ELEVENLABS\\_\\*, or OPENAI\\_API\\_KEY\\) in \\.env, optionally TTS\\_PROVIDER to pick a specific one\\.",
        "commands.voice_off": "🔇 Voice mode off",
        "commands.voice_on": "🔊 Voice mode on",
        "commands.window_gone": "❌ Window '{name}' no longer exists.",
        "commands.window_not_exist": "❌ Window '{name}' does not exist.",
        # -- ctxp --
        "ctxp.categories": "Categories:",
        # -- csp (codex /status, shown by the panel's Context button) --
        "csp.header": "📊 Session status",
        "csp.account": "Account",
        "csp.permissions": "Permissions",
        "csp.mode": "Mode",
        "csp.weekly_limit": "Weekly limit",
        # -- dirb --
        "dirb.change_folder": "📂 Change folder",
        "dirb.winp_header": "*Bind to Existing Window*\n\nThese windows are running but not bound to any topic.\nPick one to attach it here, or start a new session.\n",
        "dirb.new_session": "➕ New Session",
        "dirb.header": "*Select Working Directory*\n\nCurrent: `{path}`\n\nTap a folder to enter, or take the current one (“✅ Use this folder”)",
        "dirb.header_empty": "*Select Working Directory*\n\nCurrent: `{path}`\n\n_(No subdirectories)_",
        "dirb.up": "⬆️ Up",
        "dirb.select_here": "✅ Use this folder",
        "dirb.resume_header": "*Which agent to run?*\n",
        "dirb.resume_found": "Resume a saved conversation or start a new one:",
        "dirb.no_sessions": "No saved conversations with this agent here yet.",
        "dirb.ts_now": "now",
        "dirb.ts_min": "{n}m",
        "dirb.ts_hour": "{n}h",
        "dirb.ts_day": "{n}d",
        "dirb.new_session_on": "➕ New session — {agent}",
        "dirb.agent_row": "🤖 Agent: {agent} ▾",
        "dirb.sessions_n": "{n} sess.",
        "dirb.back": "← Back",
        # -- fwd --
        "fwd.no_session": "❌ No session bound to this topic. Send a regular message and I'll offer to pick a folder and start one.",
        "fwd.sent": "⚡ [{name}] Sent: {cmd}\nSee the result in the 👾 Agent panel.",
        # -- hist --
        "hist.older": "◀ Older",
        "hist.newer": "Newer ▶",
        # -- iui --
        "iui.btn_open_login": "🔗 Open sign-in",
        "iui.btn_refresh": "🔄 Refresh",
        "iui.caption_waiting": "❓ *Agent is waiting for a reply*",
        "iui.login_prompt": "🔐 *Sign in*\n\nOpen the link and sign in to your account.\n\n`{url}`",
        "iui.login_code": "One-time code (enter it where prompted):\n`{code}`",
        "iui.plan_header": "📋 *Plan awaiting approval* — read it, then answer with the keys under the photo below:",
        # -- lboard --
        # -- links --
        "links.header": "🔗 Links",
        "links.overflow": "… and {extra} more",
        # -- media --
        "media.unsupported": "⚠ Stickers, video and other media can't be forwarded to the agent. Text, photos, voice messages and files work.",
        "media.use_topic": "❌ Please use a named topic. Create a new topic to start a session.",
        "media.no_binding": "❌ No session bound to this topic. Send a text message first to set one up, then re-send the file.",
        "media.window_gone": "❌ Window '{name}' no longer exists. Binding removed.\nSend a message to start a new session.",
        "media.image_sent": "📷 Image sent to the agent.",
        "media.image_send_failed": "❌ Failed to send the image to the agent.",
        "media.image_echo": "👀 {agent} is looking at this image",
        "media.file_sent": "📎 File '{name}' sent to the agent.",
        "media.blocked_widget": "⚠ The agent is waiting for an answer in a dialog (the photo with buttons above). The file is saved — answer the question, then send it again.",
        "media.voice_needs_key": "⚠ Voice transcription requires an API key.\nSet `DEEPGRAM_API_KEY` or `OPENAI_API_KEY` in your `.env` file and restart the bot.",
        "media.transcribe_failed": "⚠ Transcription failed, please try again. ({err})",
        "media.archive_sent": "📦 Archive «{name}» sent to the agent — asked it to unpack it.",
        "media.download_failed": "❌ Couldn't download the file from Telegram.",
        "media.download_failed_too_big": " Looks like it's over 20 MB — split the archive into parts or send the files separately.",
        "media.file_too_big": "❌ File too large (~{mb} MB). Telegram only lets a bot download files up to 20 MB — that's a Telegram limit, not the bot's.\n\nSplit the archive into ≤20 MB parts or send the files separately.",
        "media.voice_blocked_no_text_option": '🎤 "{text}"\n\n⚠️ The agent\'s question has no free text field — pick an option with ↑↓⏎ in the 👾 Agent panel\\.',
        "media.voice_blocked_widget": '🎤 "{text}"\n\n⚠️ The agent is waiting for a reply in the dialog\\. First pick an option with the ↑↓⏎ buttons, then dictate again\\.',
        # -- mq --
        "mq.agent_looking": "👀 Agent is looking",
        "mq.code_file_caption": "📄 {filename} ({n_lines} lines)",
        "mq.diff_changes": "✏️ Changes",
        "mq.voice_budget_warning": "🔊 Voice: {used}/{limit} chars today (80% of daily limit). ≈{remaining} chars left.",
        "mq.voice_exhausted_summary": "🔇 Voice turned off in all topics — daily limit exceeded ({used}/{limit} chars). Resets at 00:00.",
        "mq.voice_exhausted_topic": "🔇 Voice turned off automatically — daily TTS limit exceeded. Resets at 00:00. Resume: /voice",
        # -- rconf --
        "rconf.agent_busy": "👍 — but the agent is busy right now, not sending anything. Reply with a word when it's free.",
        "rconf.confirmed": "👍 — confirmed",
        "rconf.sent_yes": "👍 — sent «yes» to the agent",
        # -- agentdel --
        "agentdel.confirm_tmux": "🗑 Delete agent «{name}»?\n\nThe agent stops and the topic — with every message in it — is gone for good. Files in the folder stay; the agent's own history survives, so a new agent in that folder can pick it up with «⏪ Resume».",
        "agentdel.confirm_sibling": "🗑 Delete agent «{name}»?\n\nIt's a sibling agent: it stops, and the topic — with every message in it — is gone for good. The shared files and its neighbours are untouched.",
        "agentdel.confirm_docker": "🗑 Delete agent «{name}»'s topic?\n\nThe agent itself keeps running, but the topic — with every message in it — is gone for good. To bring the agent back to the chat, create a topic named «{name}».",
        "agentdel.main_topic": "🗑 is only for extra agents — the ones started with ➕ or 🌳 beside another agent. This is the topic's own agent: to end its session use «⏹ End session», and to remove the topic delete it in Telegram.",
        "agentdel.ok": "✅ Yes, delete",
        "agentdel.err_topic": "⚠️ Agent «{name}» is stopped, but the topic couldn't be deleted — the bot lacks the delete-messages right. Close or delete the topic by hand.",
        # -- sib --
        "sib.name_prompt": "➕ One more agent beside {name}: the same files, but its own topic and its own conversation.\nSend a short name — it becomes the topic's name.",
        "sib.no_parent": "Couldn't work out which agent to create this one beside",
        "sib.err_hook": "agent «{name}»'s container can't keep siblings apart: its hook labels them with the parent's name. How to fix it — docs/docker-agents.md, the sibling-agents section",
        "sib.err_start": "couldn't start the agent in the container",
        "sib.provision_ok": "Agent created: {name}",
        "sib.welcome_docker": "➕ Done — one more agent beside {parent}, on the same files.\nIt can't see its neighbour's chat, so describe the task here 👇",
        "sib.welcome_tmux": "➕ Done — one more agent in {path}.\nIt can't see its neighbour's chat, so describe the task here 👇",
        # -- spoll --
        "spoll.agent_stopped": "⚠️ Agent *{name}* stopped. The window will be closed in {grace}s. Use /restart to restart it.",
        "spoll.sibling_down": "💤 Agent «{name}» isn't running right now — its container may have restarted. Tap «🔄 Restart» in the 👾 Agent panel to bring it back and continue.",
        "spoll.window_closed": "💀 Window *{name}* closed (the agent was down for {secs}s).",
        "spoll.model_switched": "⚠️ A model safeguard fired on the last message — the agent auto-switched to {model}. Safeguards are broad right now and can trip even on safe work (coding, cybersecurity, biology).",
        "spoll.model_switched_fallback": "another model",
        # -- wt --
        "wt.agent_deleted": "🗑 Agent «{title}» deleted.",
        "wt.agent_gone": "The agent is already gone",
        "wt.bits_ahead": "{count} unmerged commits",
        "wt.bits_dirty": "{count} unsaved files",
        "wt.bullet_ahead": "• {count} commit(s) not in {base}",
        "wt.bullet_dirty": "• {count} file(s) with unsaved edits",
        "wt.cancel": "↩ Cancel",
        "wt.cancelled": "Cancelled",
        "wt.close_guard_footer": "\n\nThe working copy is intact. What do we do?",
        "wt.close_guard_header": "⚠️ Not closing «{title}» — there's unmerged work:\n",
        "wt.copy_branch": "📋 Branch",
        "wt.copy_path": "📋 Path",
        "wt.creating": "⏳ Creating the agent…",
        "wt.del_confirm_clean": "🗑 Delete agent «{title}»?\nEverything is merged, nothing to lose — I'll remove the copy, branch and topic.",
        "wt.del_confirm_dirty": "⚠️ «{title}» has: {bits}.\nDeleting will erase this FOREVER.",
        "wt.del_ok_clean": "✅ Yes, delete",
        "wt.del_ok_dirty": "🧨 Delete and lose it",
        "wt.delete_anyway": "🧨 Delete anyway",
        "wt.deleting": "🗑 Deleting…",
        "wt.empty_name": "Empty name — cancelled.",
        "wt.err_no_base_branch": "couldn't determine the base branch (detached HEAD?)",
        "wt.err_topic_not_created": "topic not created: {error}",
        "wt.err_window": "window: {error}",
        "wt.keep_agent": "↩ Keep the agent",
        "wt.kept_msg": "↩ Kept — the agent is still here.",
        "wt.kept_toast": "↩ Kept",
        "wt.choose_runtime": "🌱 New agent in project {repo}.\nWhich agent to run in the new branch?",
        "wt.new_agent_prompt": "🌱 New agent in project {repo}.\nWrite a short name for the task — for example «header redesign». It becomes the topic and branch name; you'll set the actual task in the new topic.",
        "wt.no_project": "Can't determine this topic's project",
        "wt.not_git_repo": "{repo} — not a git repository",
        "wt.not_in_topic": "Not in a topic",
        "wt.not_worktree_agent": "This isn't a worktree agent",
        "wt.panel_agent_header": "👾 *Agent:* {name}",
        "wt.provision_failed": "❌ Failed: {info}",
        "wt.provision_ok": "Agent created: 🌳 {repo} · {title} (branch {branch})",
        "wt.welcome": "🌳 Done — a parallel agent for project {repo}.\nBranch: {branch} (a separate copy, I don't merge it into main myself).\n\nWrite the task 👇",
    }
)
